name: CI Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: List files to check for appsettings.json
      run: ls -la src/RealtorHubAPI

    - name: Create temp secrets JSON file
      run: |
        echo '{
          "Cloudinary": {
            "CloudName": "'"${{ secrets.CLOUDINARY_CLOUDNAME }}"'",
            "ApiKey": "'"${{ secrets.CLOUDINARY_APIKEY }}"'",
            "ApiSecret": "'"${{ secrets.CLOUDINARY_APISECRET }}"'"
          },
          "Minio": {
            "Endpoint": "'"${{ secrets.MINIO_ENDPOINT_STAGING }}"'",
            "AccessKey": "'"${{ secrets.MINIO_ACCESSKEY_STAGING }}"'",
            "SecretKey": "'"${{ secrets.MINIO_SECRETKEY_STAGING }}"'",
            "BucketName": "'"${{ secrets.MINIO_BUCKETNAME_STAGING }}"'"
          }
        }' > temp_secrets.json

    - name: Apply JSON Patch to appsettings.json
      run: |
        jq -s '.[0] * .[1]' src/RealtorHubAPI/appsettings.json temp_secrets.json > src/RealtorHubAPI/appsettings.Staging.json

    - name: Verify appsettings.Staging.json
      run: cat src/RealtorHubAPI/appsettings.Staging.json

    - name: Publish
      run: dotnet publish --no-restore --configuration Release --output ./publish

     #copy to server
    - name: Deploy to Staging - Copy to Server via SCP
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /home/runner/work/RealtorHubAPI/RealtorHubAPI/src/RealtorHubAPI/bin/Release/net8.0/publish/
        concurrency: 10
        remote: ${{ secrets.REMOTE_TARGET_STAGING }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
      env:
        ASPNETCORE_ENVIRONMENT: Staging
        IT_HEAD_EMAIL: ${{ secrets.IT_HEAD_EMAIL }}
        IT_HEAD_PASSWORD: ${{ secrets.IT_HEAD_PASSWORD }}
        IT_HEAD_PHONENUMBER: ${{ secrets.IT_HEAD_PHONENUMBER }}
        ROOT_ADMIN_EMAIL: ${{ secrets.ROOT_ADMIN_EMAIL }}
        ROOT_ADMIN_PHONENUMBER: ${{ secrets.ROOT_ADMIN_PHONENUMBER }}
        ROOT_DEFAULT_PASSWORD: ${{ secrets.ROOT_DEFAULT_PASSWORD }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    #start service
    - name: Start RealtorHubAPIStaging Service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: service RealtorHubAPIStaging restart
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
