name: CI Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore RealtorHubAPI.sln

    - name: Build
      run: dotnet build RealtorHubAPI.sln --no-restore --configuration Release

    - name: Substitute Environment Variables in appsettings.Staging.json
      uses: microsoft/variable-substitution@v1
      with:
        files: src/RealtorHubAPI/appsettings.Staging.json
      env:
        Cloudinary.CloudName: ${{ secrets.CLOUDINARY_CLOUDNAME }}
        Cloudinary.ApiKey: ${{ secrets.CLOUDINARY_APIKEY }}
        Cloudinary.ApiSecret: ${{ secrets.CLOUDINARY_APISECRET }}
        Minio.Endpoint: ${{ secrets.MINIO_ENDPOINT_STAGING }}
        Minio.AccessKey: ${{ secrets.MINIO_ACCESSKEY_STAGING }}
        Minio.SecretKey: ${{ secrets.MINIO_SECRETKEY_STAGING }}
        Minio.BucketName: ${{ secrets.MINIO_BUCKETNAME_STAGING }}

    - name: Verify appsettings.Staging.json
      run: cat src/RealtorHubAPI/appsettings.Staging.json

    - name: Publish
      run: dotnet publish RealtorHubAPI.sln --no-restore --configuration Release --output src/RealtorHubAPI/bin/Release/net8.0/publish

    - name: Verify publish directory
      run: ls -la src/RealtorHubAPI/bin/Release/net8.0/publish

    # Copy to server
    - name: Deploy to Staging - Copy to Server via SCP
      uses: garygrossgarten/github-action-scp@release
      with:
        local: src/RealtorHubAPI/bin/Release/net8.0/publish/
        concurrency: 10
        remote: ${{ secrets.REMOTE_TARGET_STAGING }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}

    # Start service
    - name: Start RealtorHubAPIStaging Service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: service RealtorHubAPIStaging restart
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
