name: CI/CD Staging Docker

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Substitute ConnectionString in appsettings.Staging.json
        run: |
          sed -i 's|"DefaultConnection": ".*"|"DefaultConnection": "${{ secrets.DB_CONNECTION }}"|' src/RealtorHubAPI/appsettings.Staging.json

      - name: Substitute Environment Variables in appsettings.Staging.json
        uses: microsoft/variable-substitution@v1
        with:
          files: src/RealtorHubAPI/appsettings.Staging.json
        env:
          Cloudinary.CloudName: ${{ secrets.CLOUDINARY_CLOUDNAME }}
          Cloudinary.ApiKey: ${{ secrets.CLOUDINARY_APIKEY }}
          Cloudinary.ApiSecret: ${{ secrets.CLOUDINARY_APISECRET }}
          Minio.Endpoint: ${{ secrets.MINIO_ENDPOINT_STAGING }}
          Minio.AccessKey: ${{ secrets.MINIO_ACCESSKEY_STAGING }}
          Minio.SecretKey: ${{ secrets.MINIO_SECRETKEY_STAGING }}
          Minio.BucketName: ${{ secrets.MINIO_BUCKETNAME_STAGING }}
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION }}


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/RealtorHubAPI/Dockerfile
          push: true
          tags: abdulquddusnuhu/realtorhubapi:staging

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "docker-compose.yml"
          target: ${{ secrets.REMOTE_TARGET_STAGING }}

      - name: Copy config files to server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "config/*"
          target: "${{ secrets.REMOTE_TARGET_STAGING }}/config"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: List files in target directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            ls -al ${{ secrets.REMOTE_TARGET_STAGING }}/config

      - name: Verify Docker Compose Installation
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            docker compose version

      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            docker pull abdulquddusnuhu/realtorhubapi:staging
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"
            echo "JWT_SECRET_KEY is '$JWT_SECRET_KEY'"
            docker compose -f ${{ secrets.REMOTE_TARGET_STAGING }}/docker-compose.yml down
            docker compose -f ${{ secrets.REMOTE_TARGET_STAGING }}/docker-compose.yml up -d
